# ArUco dictionary (e.g. 5 → DICT_5X5_100)
marker_dictionary:       2

# Physical marker side length (meters)
marker_size:            0.20

# Complementary‐filter gain (how much to trust ArUco vs. odom)
alpha:                  0.20

# Minimum movement before publishing (meters)
movement_threshold:     0.10

# Minimum rotation before publishing (degrees)
rotation_threshold_deg:  5.0

# Minimum time between updates (seconds)
update_interval:        2.0

# Known world poses of each marker (x, y in meters; yaw in degrees)
marker_positions:
  - {id: 10, x:  6.60, y:  1.25, yaw:   90.0}
  - {id: 15, x:  3.20, y:  3.85, yaw:   90.0}
  - {id: 20, x:  3.80, y:  0.10, yaw:   90.0}
  - {id: 25, x:  2.00, y:  0.02, yaw:   90.0}
  - {id: 30, x:  2.00, y:  3.80, yaw:   90.0}
  - {id: 35, x:  0.00, y:  2.40, yaw:    0.0}
  - {id: 40, x:  0.00, y:  4.20, yaw:    0.0}
  - {id: 45, x:  0.00, y:  6.00, yaw:    0.0}
  - {id: 50, x:  0.00, y:  7.20, yaw:    0.0}
  - {id: 55, x:  0.10, y:  9.84, yaw:  -90.0}
  - {id: 60, x:  2.00, y:  9.94, yaw:  -90.0}
  - {id: 65, x:  5.00, y:  9.94, yaw:  -90.0}
  - {id: 70, x:  6.60, y:  9.84, yaw:  -90.0}
  - {id: 75, x:  6.80, y:  7.20, yaw:  180.0}
  - {id: 80, x:  6.80, y:  5.10, yaw:  180.0}
  - {id: 85, x:  6.80, y:  3.00, yaw:  180.0}
