# landmarks.yaml - Landmark configuration file
landmarks:
  - id: 1
    x: 1.0
    y: 0.0
    description: "ArUco marker 1"
  - id: 2
    x: 0.5
    y: 0.5
    description: "ArUco marker 2"
  - id: 3
    x: 0.0
    y: 1.0
    description: "ArUco marker 3"
  - id: 4
    x: 1.5
    y: 1.5
    description: "ArUco marker 4 (spare)"

# topics.txt - Topic configuration file
odometry: /pepper/odom
imu: /pepper/imu
camera: /realsense/color/image_raw
head_yaw: /pepper/joint_states/head_yaw