landmarks:
  - id: 10
    x: 6.6
    y: 1.25
    description: "ArUco marker 10"
  - id: 15
    x: 3.2
    y: 3.85
    description: "ArUco marker 15"
  - id: 20
    x: 3.8
    y: 0.1
    description: "ArUco marker 20"
  - id: 25
    x: 2.0
    y: 0.02
    description: "ArUco marker 25"
  - id: 30
    x: 2.0
    y: 3.8
    description: "ArUco marker 30"
  - id: 35
    x: 0.0
    y: 2.4
    description: "ArUco marker 35"
  - id: 40
    x: 0.0
    y: 4.2
    description: "ArUco marker 40"
  - id: 45
    x: 0.0
    y: 6.0
    description: "ArUco marker 45"
  - id: 50
    x: 0.0
    y: 7.2
    description: "ArUco marker 50"
  - id: 55
    x: 0.1
    y: 9.84
    description: "ArUco marker 55"
  - id: 60
    x: 2.0
    y: 9.94
    description: "ArUco marker 60"
  - id: 65
    x: 5.0
    y: 9.94
    description: "ArUco marker 65"
  - id: 70
    x: 6.6
    y: 9.84
    description: "ArUco marker 70"
  - id: 75
    x: 6.8
    y: 7.2
    description: "ArUco marker 75"
  - id: 80
    x: 6.8
    y: 5.1
    description: "ArUco marker 80"
  - id: 85
    x: 6.8
    y: 3.0
    description: "ArUco marker 85"