# Aruco marker configuration file
marker_positions:
  - {id: 10, x:  6.60, y:  1.25, theta:   90.0}
  - {id: 15, x:  3.20, y:  3.85, theta:   90.0}
  - {id: 20, x:  3.80, y:  0.10, theta:   90.0}
  - {id: 25, x:  2.00, y:  0.02, theta:   90.0}
  - {id: 30, x:  2.00, y:  3.80, theta:   90.0}
  - {id: 35, x:  0.00, y:  2.40, theta:    0.0}
  - {id: 40, x:  0.00, y:  4.20, theta:    0.0}
  - {id: 45, x:  0.00, y:  6.00, theta:    0.0}
  - {id: 50, x:  0.00, y:  7.20, theta:    0.0}
  - {id: 55, x:  0.10, y:  9.84, theta:  -90.0}
  - {id: 60, x:  2.00, y:  9.94, theta:  -90.0}
  - {id: 65, x:  5.00, y:  9.94, theta:  -90.0}
  - {id: 70, x:  6.60, y:  9.84, theta:  -90.0}
  - {id: 75, x:  6.80, y:  7.20, theta:  180.0}
  - {id: 80, x:  6.80, y:  5.10, theta:  180.0}
  - {id: 85, x:  6.80, y:  3.00, theta:  180.0}