landmarks:
  - id: 1
    x: 4.0
    y: 3.6
    z: 0.71
  - id: 2
    x: 2.0
    y: 6.6
    z: 0.71
  - id: 3
    x: 2.0
    y: 4.8
    z: 0.71
  # - id: 4
  #   x:
  #   y:
  #   z:
  # - id: 5
  #   x:
  #   y:
  #   z:
  # - id: 10
  #   x: 6.6
  #   y: 1.25
  #   z: 1.64
  - id: 15
    x: 3.2
    y: 3.85
    z: 0.61
  # - id: 20
  #   x: 3.8
  #   y: 0.1
  #   z: 1.40
  # - id: 25
  #   x: 2.0
  #   y: 0.02
  #   z: 1.74
  # - id: 30
  #   x: 2.0
  #   y: 3.8
  #   z: 0.61
  # - id: 35
  #   x: 0.0
  #   y: 2.4
  #   z: 1.74
  # - id: 40
  #   x: 0.0
  #   y: 4.2
  #   z: 1.72
  # - id: 45
  #   x: 0.0
  #   y: 6.0
  #   z: 1.74
  # - id: 50
  #   x: 0.0
  #   y: 7.2
  #   z: 1.74
  # - id: 55
  #   x: 0.1
  #   y: 9.84
  #   z: 1.72
  # - id: 60
  #   x: 2.0
  #   y: 9.94
  #   z: 0.86
  # - id: 65
  #   x: 5.0
  #   y: 9.94
  #   z: 0.86
  # - id: 70
  #   x: 6.6
  #   y: 9.84
  #   z: 1.67
  # - id: 75
  #   x: 6.8
  #   y: 7.2
  #   z: 1.72
  # - id: 80
  #   x: 6.8
  #   y: 5.1
  #   z: 1.71
  # - id: 85
  #   x: 6.8
  #   y: 3.0
  #   z: 1.67